### PR TITLE
Fix stats spending trend

### LINKED ISSUE #152: [PE-D][Tester D] stats command shows 'Spending Trend' with no explanation of what it mean
Steps to reproduce:
1. Launch the app
2. Add a few transactions
3. Type: stats

Expected: Spending Trend value is explained e.g. what time period it covers, how it is calculated
Actual: "Spending Trend: Decreasing" is shown with no explanation

The UG lists "spending trend" as a stats output but never explains what it means, how it is calculated, or what time period it covers. A user has no way to interpret this value meaningfully.

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #160: [PE-D][Tester A] Spending trend incorrectly shows "Decreasing" when all expenses are in the same month
## Description:
- When all recorded expense transactions fall within the same month, the `stats` command reports the spending trend as "Decreasing" instead of "Stable".

## Steps to reproduce:

```
Enter a command: add food/10
Added: [Expense] food $10.00 (2026-04-10)

Enter a command: add transport/20
Added: [Expense] transport $20.00 (2026-04-10)

Enter a command: stats
====== Statistics ======
Total Income: $0.00
Total Expense: $40.00

Highest Expense: [Expense] transport $20.00 (2026-04-10)
Lowest Expense: [Expense] food "lunch" $10.00 (2026-04-10)
Highest Income: N/A

Most Frequent Category: food

Average Spending per Category:
food: $10.00
transport: $20.00

Spending Trend: Decreasing

Budget Used: No budget set
========================

Enter a command:

```

## Expected: 
- Spending trend should be "Stable" or "Not enough data"  as all expenses are in the same month and there is no second month to compare against.

## Actual: 
- `Spending Trend: Decreasing` 
- This information seems misleading and incorrect.

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by CedricTan24**
Fix spending trend logic in stats and update Developer Guide.

- Updated getSpendingTrend() to group expenses by month and compare earliest vs latest month
- Return "Not enough data" when there are fewer than two distinct expense months
- Prevent misleading results such as "Decreasing" when all expenses fall within the same month
- Added/updated tests for spending trend scenarios
- Updated DG to document the improved month-based trend calculation and design considerations

Fixes #152 
Fixes #160

### CODE REVIEW

File: src/main/java/seedu/duke/transactionlist/TransactionList.java [hunk 1]
```diff
@@ -181,27 +182,25 @@ public HashMap<String, Double> getAverageSpendingPerCategory() {
...
-        if (transactions.size() < 2) {
-            return "Not enough data";
-        }
-
-        double earlier = 0;
-        double later = 0;
-
-        YearMonth firstMonth = YearMonth.from(transactions.get(0).getDate());
-        YearMonth lastMonth = YearMonth.from(transactions.get(transactions.size() - 1).getDate());
+        Map<YearMonth, Double> monthTotals = new HashMap<>();
```
Comment (Nishuy52) [inline src/main/java/seedu/duke/transactionlist/TransactionList.java:185]: Solid fix to the original guard. The old `transactions.size() < 2` check ran before filtering by expense type, so a list with two incomes (and no expenses) would incorrectly pass it. Checking `monthTotals.size() < 2` after aggregating expense months is semantically correct.

File: src/main/java/seedu/duke/transactionlist/TransactionList.java [hunk 2]
```diff
@@ -181,27 +182,25 @@ public HashMap<String, Double> getAverageSpendingPerCategory() {
...
+                YearMonth month = YearMonth.from(t.getDate());
+                monthTotals.put(month, monthTotals.getOrDefault(month, 0.0) + t.getAmount());
             }
         }
 
+        if (monthTotals.size() < 2) {
+            return "Not enough data";
+        }
+
+        YearMonth earliest = Collections.min(monthTotals.keySet());
```
Comment (Nishuy52) [inline src/main/java/seedu/duke/transactionlist/TransactionList.java:198]: The method compares only the earliest and latest expense months. With 3+ months of data (e.g., Jan=$10, Feb=$500, Mar=$8) this reports `Decreasing` despite a large mid-period spike. Consider documenting this as a known limitation in the DG section you are updating — something like "trend compares the earliest and latest recorded expense months" — so the behaviour is intentional rather than surprising.

File: src/main/java/seedu/duke/transactionlist/TransactionList.java [hunk 3]
```diff
@@ -181,27 +182,25 @@ public HashMap<String, Double> getAverageSpendingPerCategory() {
...
+        YearMonth latest = Collections.max(monthTotals.keySet());
```
Comment (Nishuy52) [inline src/main/java/seedu/duke/transactionlist/TransactionList.java:199]: Clean use of `Collections.min/max` on `monthTotals.keySet()` — `YearMonth` implements `Comparable<YearMonth>` so its natural ordering works here without a custom comparator.

**Review by Nishuy52 — COMMENTED** [review]
CS2113 review: 1 logic concern, 2 positive notes.

Additional note: this PR's diff includes all the changes from PR #197 (`DeleteCommand.java`, `DeleteCommandTest.java`, `ParserTest.java`, `EXPECTED.TXT`), meaning `fix-stats-spending-trend` was likely branched from `fix-delete-empty-list-message`. To avoid a merge conflict, merge #197 first and then update this branch from master before merging.

**Review by Nishuy52 — APPROVED** [review]
LGTM
