### PR TITLE
Fix delete command index validation

### LINKED ISSUE #163: [PE-D][Tester A] Delete error message shows  a strange "between 1 and 0" message on empty list
## Description:
- When a user tries to delete a transaction from an empty list, the error message says "Please provide a number between 1 and 0",

## Steps to reproduce:
- Launch app with no existing data file. 
- 
```
       .___.
       /     \
      |       |
      `-.   .-`
     /   \ /   \
    |   $$$$$   |
    |  $$$$$$$  |
    |   $$$$$   |
     \         /
      `-------`
____________________________________________________________
Welcome to MoneyBagProMax, give us your money.
Enter `help` to check the list of available commands.
____________________________________________________________

Enter a command: delete 1
[ERROR!] Invalid transaction index. Please provide a number between 1 and 0.
```

## Expected: 
- A clear error message such as "No transactions to delete" or "The transaction list is empty."

## Actual: 
- `[ERROR!] Invalid transaction index. Please provide a number between 1 and 0.` 
- The range "1 to 0" is confusing and challenging  for the users to understand.

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #182: [PE-D][Tester C] Error message for attempts to delete entries at 0 entries can be improved
Image

when I tried to run "delete 1" when there is 0 entries the error message is "[ERROR!] Invalid transaction index. Please provide a number between 1 and 0." suggesting that 0 is a valid input after delete. however when i input "delete 0" the same error message is displayed. Since the entry index starts at 1 delete 0 command can cause confusion hence the correct error message should be there is no entries in the list for deletion.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### PR DESCRIPTION
**Pull request by CedricTan24**
Fix delete command validation.

- Fix delete index handling

Fixes #182 
Fixes #163

### CODE REVIEW

File: src/main/java/seedu/duke/command/DeleteCommand.java [hunk 1]
```diff
@@ -24,6 +24,10 @@ public void execute(TransactionList list, Budget budget, Ui ui) throws MoneyBagP
 
         int listIndex = targetIndex - 1;
 
+        if (list.isEmpty()) {
```
Comment (Nishuy52) [inline src/main/java/seedu/duke/command/DeleteCommand.java:27]: Good UX fix — the old code produced the confusing "provide a number between 1 and 0" message when the list was empty. Giving this its own guard with a clear message is the right call.

File: src/test/java/seedu/duke/command/DeleteCommandTest.java [hunk 2]
```diff
@@ -92,4 +93,16 @@ public void execute_emptyList_throwsException() {
 
         assertThrows(MoneyBagProMaxException.class, () -> command.execute(list, budget, ui));
     }
+
+    @Test
+    void execute_emptyList_throwsEmptyListMessage() {
```
Comment (Nishuy52) [inline src/test/java/seedu/duke/command/DeleteCommandTest.java:91]: This test covers the same scenario as `execute_emptyList_throwsException` directly above (which only checks that *some* `MoneyBagProMaxException` is thrown). Since asserting the message content is strictly stronger, consider removing the older test and keeping only this one to avoid two tests exercising the exact same code path.

File: src/test/java/seedu/duke/parser/ParserTest.java [hunk 3]
```diff
@@ -151,7 +151,7 @@ public void parseFilterCommand_invalidDateFormat_throwsException() {
         String input = "filter from/31-12-2026 to/2026-12-31";
 
         MoneyBagProMaxException exception = assertThrows(MoneyBagProMaxException.class, () -> parser.parse(input));
```
Comment (Nishuy52) [inline src/test/java/seedu/duke/parser/ParserTest.java:153]: This loosens the assertion from the exact message `"Invalid date format — expected YYYY-MM-DD."` to just `"Invalid date format"`, but that change is unrelated to the delete command fix. If the parser error message format changed, that should appear in its own commit/PR with an explanation.

**Review by Nishuy52 — COMMENTED** [review]
CS2113 review: 2 logic concerns, 1 standards issue, 1 positive note.

Note: this PR also contains changes from PR #198 (`TransactionList.java` spending trend rewrite, `TransactionListTest.java` new tests, `DeveloperGuide.md`). Both PRs touch `ParserTest.java` and `DeleteCommandTest.java` — merge this one first, then update #198 from master before merging.

**Review by Nishuy52 — APPROVED** [review]
LGTM
